-- Your SQL goes here

CREATE TABLE "user"
(
    "id"        INT GENERATED BY DEFAULT AS IDENTITY,
    "email"     VARCHAR(128) UNIQUE NOT NULL,
    "username"  VARCHAR(64) UNIQUE  NOT NULL,
    "password"  VARCHAR(64)         NOT NULL,
    "joined_at" TIMESTAMP           NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

CREATE TABLE "session"
(
    "token"      CHAR(256),
    "expires_at" TIMESTAMP NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "user_id"    INT       NOT NULL,
    PRIMARY KEY ("token"),
    CONSTRAINT "fk_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
